--INSERTAR USUARIO NUEVO
DELIMITER //
CREATE PROCEDURE SP_CREATE_USUARIO(IN $CORREO VARCHAR(100),IN $CONTRASENA VARCHAR(250),IN $ID_PERFIL INT )
BEGIN
	INSERT INTO `maipo_grande`.`usuario`
(`CORREO`,
`CONTRASENA`,
`ID_PERFIL`)
VALUES
($CORREO,
$CONTRASENA,
$ID_PERFIL); 

END //

DELIMITER ;



