#USAR LA BD PARA LA CREACION
USE MAIPO_GRANDE;
#ELIMINAR PROCEDIMIENTOS EXISTENTES

#CREACION DE PROCEDIMIENTOS

#PROCEDIMIENTO DE CREACION DE USUARIOS
DROP PROCEDURE SP_CREATE_USUARIO;
DELIMITER //
CREATE PROCEDURE SP_CREATE_USUARIO(
IN $NOMBRE VARCHAR(100),
IN $APELLIDO VARCHAR(100),
IN $RUT INT(8),
IN $DV CHAR(1),
IN $COMUNA INT,
IN $CODIGO_POSTAL INT,
IN $CORREO VARCHAR(100),
IN $CONTRASENA VARCHAR(250),
IN $TELEFONO INT(11),
IN $ID_TIPO_PERSONA INT(11),
IN $NOMBRE_FANTASIA VARCHAR(100),
IN $ID_PERFIL INT(11))
BEGIN
	DECLARE $ID_USUARIO INT;
	#SE CREA NUEVO USUARIO
    INSERT INTO `maipo_grande`.`usuario`
	(`CORREO`,
	`CONTRASENA`,
	`ID_PERFIL`)
	VALUES
	($CORREO,
	$CONTRASENA,
	$ID_PERFIL); 
	#SE OBTIENE ID DE USUARIO CREADO
    SELECT MAX(ID_USUARIO) INTO $ID_USUARIO FROM `maipo_grande`.`usuario`;
    #SE INSERTAN DATOS DE PERSONA, CON EL ID DE USUARIO OBTENIDO
    INSERT INTO `maipo_grande`.`persona`
	(`ID_USUARIO`,
	`RUT`,
	`DIGITO_VERIFICADOR`,
	`NOMBRE`,
	`APELLIDO`,
	`NOMBRE_FANTASIA`,
	`CODIGO_POSTAL`,
	`ID_COMUNA`,
	`TELEFONO`,
	`ID_TIPO_PERSONA_LEGAL`)
	VALUES
	($ID_USUARIO,
	$RUT,
	$DV,
	$NOMBRE,
	$APELLIDO,
	$NOMBRE_FANTASIA,
	$CODIGO_POSTAL,
	$COMUNA,
	$TELEFONO,
	$ID_TIPO_PERSONA);
END //
DELIMITER ;

#PROCEDIMIENTO CON OFERTAS PARA CATALOGO, SEGUN ROL
DROP PROCEDURE SP_GET_CATALOGO;
DELIMITER //
CREATE PROCEDURE SP_GET_CATALOGO(
IN $ID_PERFIL INT
)
BEGIN
	IF $ID_PERFIL = (2) THEN
		SELECT 
        CONCAT(PU.NOMBRE,' ',PU.APELLIDO) NOMBRE_COMPRADOR,
		TF.NOMBRE TIPO_FRUTA,
        C.NOMBRE CALIDAD,
        DP.CANT_KG,
        P.FECHA_CREACION        
		FROM PEDIDO P
        JOIN PERSONA PU ON PU.ID_USUARIO=P.ID_COMPRADOR
        JOIN DETALLE_PEDIDO DP ON P.ID_PEDIDO=DP.ID_PEDIDO
        JOIN CALIDAD C ON C.ID_CALIDAD=DP.ID_ID_CALIDAD
        JOIN TIPO_FRUTA TF ON TF.ID_TIPO_FRUTA=DP.ID_TIPO_FRUTA
        WHERE ID_ESTADO_PEDIDO IN (2)
        AND TIPO_PEDIDO=2;
	ELSEIF $ID_PERFIL = (3) OR $ID_PERFIL =(0) THEN
		SELECT 
        CONCAT(PU.NOMBRE,' ',PU.APELLIDO) NOMBRE_VENDEDOR,
		TF.NOMBRE TIPO_FRUTA,
        C.NOMBRE CALIDAD,
        DP.CANT_KG,
        P.FECHA_CREACION        
		FROM PEDIDO P
        JOIN PERSONA PU ON PU.ID_USUARIO=P.ID_COMPRADOR
        JOIN DETALLE_PEDIDO DP ON P.ID_PEDIDO=DP.ID_PEDIDO
        JOIN CALIDAD C ON C.ID_CALIDAD=DP.ID_ID_CALIDAD
        JOIN TIPO_FRUTA TF ON TF.ID_TIPO_FRUTA=DP.ID_TIPO_FRUTA
        WHERE ID_ESTADO_PEDIDO=2
        AND TIPO_PEDIDO=1;
	ELSEIF $ID_PERFIL = (4) THEN
		SELECT 
		TF.NOMBRE TIPO_FRUTA,
        C.NOMBRE CALIDAD,
        DP.CANT_KG,
        P.FECHA_CREACION,
        P.FECHA_LIMITE_O_RETIRO FECHA_LIMITE
		FROM PEDIDO P
        JOIN PERSONA PU ON PU.ID_USUARIO=P.ID_COMPRADOR
        JOIN DETALLE_PEDIDO DP ON P.ID_PEDIDO=DP.ID_PEDIDO
        JOIN CALIDAD C ON C.ID_CALIDAD=DP.ID_ID_CALIDAD
        JOIN TIPO_FRUTA TF ON TF.ID_TIPO_FRUTA=DP.ID_TIPO_FRUTA
        WHERE ID_ESTADO_PEDIDO IN (1,2)
        AND TIPO_PEDIDO=2;
    ELSEIF $ID_PERFIL = (5) THEN
		SELECT 
		CONCAT(PU.NOMBRE,' ',PU.APELLIDO) NOMBRE_VENDEDOR,
		TF.NOMBRE TIPO_FRUTA,
        C.NOMBRE CALIDAD,
        DP.CANT_KG,
        P.FECHA_CREACION
		FROM PEDIDO P
        JOIN PERSONA PU ON PU.ID_USUARIO=P.ID_COMPRADOR
        JOIN DETALLE_PEDIDO DP ON P.ID_PEDIDO=DP.ID_PEDIDO
        JOIN CALIDAD C ON C.ID_CALIDAD=DP.ID_ID_CALIDAD
        JOIN TIPO_FRUTA TF ON TF.ID_TIPO_FRUTA=DP.ID_TIPO_FRUTA
        WHERE ID_ESTADO_PEDIDO IN (2)
        AND TIPO_PEDIDO=2;
    END IF;
END //
DELIMITER ;
